### ISSUE TITLE
Input do /Query da API

### ISSUE THREAD

**Issue by netojoaobatista** [mundipagg/documentacao#2]
Quais são os possíveis `identifierName` de entrada do `/Query`?

**Comment by matheusriboli** [comment]
Boa noite João.
Os possíveis identificadores são os seguintes:
OrderKey
OrderReference
CreditCardTransactionKey (não implementado ainda)
CreditCardTransactionReference (não implementado ainda)
BoletoTransactionKey (não implementado ainda)
BoletoTransactionReference (não implementado ainda)

**Comment by netojoaobatista** [comment]
@matheusriboli 

1. Colocar todas as possibilidades
2. Colocar **apenas** as já implementadas e depois, conforme implementado, adicionar as outras

O que acha melhor: 1 ou 2?

**Comment by matheusriboli** [comment]
Acho que seria melhor colocar apenas as implementadas.
Caso contrário os clientes poderiam tentar utilizar os identificadores não implementados e não conseguir integrar corretamente.

**Comment by netojoaobatista** [comment]
Combinado.
