### ISSUE TITLE
Incluir exemplos simples de integração.

### ISSUE THREAD

**Issue by netojoaobatista** [mundipagg/documentacao#6]
Acho que seria muito bom incluir alguns exemplos mais simples de requisições, com os dados mínimos para criar uma transação.

**Comment by mvrmoreira** [comment]
Isso não estaria no apiary?

Atenciosamente,
Matheus Moreira

Em 8 de janeiro de 2015 10:12, João Batista Neto <notifications@github.com>
escreveu:

**Comment by netojoaobatista** [comment]
Não estamos usando Apiary, @mvrmoreira.

**Comment by mvrmoreira** [comment]
=(

Atenciosamente,
Matheus Moreira

2015-01-08 10:51 GMT-02:00 João Batista Neto <notifications@github.com>:
